name: Code cheks

on:
  push:
    branches: [ master ]
  pull_reqest: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - users: actions/chekout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          puthon-version: 3.12
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install - r requirements.txt
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy . 
        
